### ISSUE TITLE
map does not work and fzf-quickfix not avilable

### ISSUE THREAD

**Issue by gauteh** [fszymanski/fzf-quickfix#2]
Seems like the plugins isn't loaded, I use vim-plug:

```
if !executable('fzf')
  Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --bin' }
endif
Plug 'junegunn/fzf.vim'
Plug 'fszymanski/fzf-quickfix'

``` 

I cannot use `\q` or call any of the functions directly.

Should the map work from all buffers or just from the FZF window?

**Comment by gauteh** [comment]
It works if I remove the `g:loaded_fzf` check.

**Comment by gauteh** [comment]
Filip Szymański writes on August 6, 2018 22:25:
> If you do something like this:
> ```
> if !executable('fzf')
>   Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --bin' }
> endif
> ```
> `vim-plug` only loads the plugin when (Neo)vim can not find the `fzf` executable in the `$PATH`.
> The `g:loaded_fzf` variable is not set and the `fzf-quickfix` plugin does not work.

Yes, I do this because I want to automatically install fzf locally if I 
deploy my vim config on system without FZF. I thought that fzf-quickfix 
only needs the `fzf.vim` plugin? 

Perhaps it would be better to do a similar check in fzf-quickfix (depend 
on the executable and not the fzf plugin) and note in the README that 
fzf is required with the Plug example? So that if fzf is installed 
system-wide it also works.

> 
> When it comes to the key mapping, maybe you already have something 
> assigned to `<Leader>q` in normal mode.
> 

The key map also works if I remove the g:loaded_fzf check.

**Comment by fszymanski** [comment]
`fzf-quickfix` does not require `fzf.vim` to work. However, it uses the [fzf#run](https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim#L347) and [fzf#wrap](https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim#L276) function from the [fzf](https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim) plugin.

I completely forgot to complete the `doc.txt` and `README.md` file.
