### ISSUE TITLE
Trigger automatically when the quickfix is shown

### ISSUE THREAD

**Issue by svanharmelen** [fszymanski/fzf-quickfix#3]
This looks like a very nice plugin! Thank you for making it 👍 

I just installed it and am trying to figure out how it's supposed to work. I was hoping that it would take precedence over the quickfix window so that when another plugin would fill and open the quickfix list, the FZF window would be opened instead.

But that doesn't seem to be the case. The quickfix window is still opened and then I have to manually call this plugin to open the FZF window which then opens below the already open quickfix window.

Is that how its supposed to work? And/or is there a way to change the behavior to make it work as I was hoping?

Thanks!

**Comment by dofinn** [comment]
+1. I can not seem to find a way to replace the default quickfix pop up with :Quickfix. Any suggestions?

**Comment by fszymanski** [comment]
@dofinn you can try to use the `QuickfixCmdPost` event and do something like this:
```vim
autocmd QuickfixCmdPost * ++nested cclose | Quickfix
```
However, to avoid jumping to the first error add `!` to commands like `:make`, `:grep`, etc.

**Comment by dofinn** [comment]
thanks for the response @fszymanski 

It nearly works for my use-case. I am having issues with it going smoothly with errors generated by `:GoTest!` from vim-go. Below is the output, it seems to open up to Quickfix windows, but both are un-usable. 

```
    0   hello_test.go|10| got "Hello, World" want "Hello, world"
    1 > || TestHello                               
    2   2/2                                                              
    3 QfList>                                                              
 > fzf                                                                                                    
    1 || TestHello                                                                                        
    2 hello_test.go|10| got "Hello, World" want "Hello, world"
 Quickfix  GoTest                                                     [unix]   50% ☰    1/2  :  4 
E21: Cannot make changes, 'modifiable' is off
```
