### ISSUE TITLE
Add the ability to search for quickfix history

### ISSUE THREAD

**Issue by Shatur95** [fszymanski/fzf-quickfix#4]
Quickfix lists can have histoy (`:chi[story]`). Is it possible to add the ability to select specific quickfix from history via fzf? It would be very useful to switch between compilation output and search.

**Comment by Shatur95** [comment]
I can send a PR if you like the idea.

**Comment by fszymanski** [comment]
I won't work further on this plugin as I don't use (neo)vim anymore. I'm very sorry.

**Comment by Shatur95** [comment]
@fszymanski, okay, thanks for letting know!
